spring: 
    profiles: 
        active: -dev
       
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-dev version=1
        
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-test version=1
